random_seed: 42
cloud_storage:
  credentials: keys/google.json
  bucket_name: pet_project
  images_folder: "pet_images"
  project_name: "nlp-masters-project"
  output_folder: "trainer_output"

data:
  local_images_folder: "data/pet_images"
  classes_text_file: "data/text_info/classes.csv"
  train_fracture: 0.7
  val_fracture: 0.2
  test_fracture: 0.1
  train_classes_file: "data/text_info/train.csv"
  val_classes_file: "data/text_info/val.csv"
  test_classes_file: "data/text_info/test.csv"
  train_h5_file: "data/datasets/train.hdf5"
  val_h5_file: "data/datasets/val.hdf5"
  test_h5_file: "data/datasets/test.hdf5"
  feature_extractor: "microsoft/resnet-18"
  visualization_output_path: "data/test_visualization.png"

augmentations:
  image_size: 224
  rotate_abs_angle: 25
  noise_lower_bound: 10
  noise_upper_bound: 30
  dropout_p: 0.01
  salt_and_pepper_p: 0.02
  blur_lower_kernel_bound: 1
  blur_upper_kernel_bound: 5
  jpeg_compression_bounds: [50, 80]
  motion_blur_bounds: [3, 7]
  gaussian_blur_bounds: [0, 3]
  color_multiplier: [0.7, 1.5]
  contrast_bounds: [0.7, 1.4]
  clahe_clip_limit: [0.1, 4]


  rotate_probability: 0.5
  arithmetic_probability: 0.5
  blur_probability: 0.5
  color_probability: 0.5
  contrast_probability: 0.5

model:
  output_vector_size: 64
  triplet_loss_alpha: 1.0
  pretrained_model_name: "microsoft/resnet-18"

trainer:
  eval_steps: 30
  train_batch_size: 8
  val_batch_size: 8
  epochs: 100
  learning_rate: 0.001
  weight_decay : 0.0015
  save_steps: 400
  fp16: True
  gradient_accumulation_steps: 1
  eval_accumulation_steps: 1
  trainer_checkpoint: ""
  output_folder: "output"
  loss_function: "mse"
  experiment_name: "resnet_18_baseline"
  compute_test_metrics: False
  tensorboard_log: "output/tensorboard/latest"

score:
  onnx_output_filepath: "model.onnx"
